# Generated by Django 3.2.7 on 2022-05-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5, verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Building Title')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, verbose_name='Apartment Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('apartment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS_app.apartmenttype')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMS_app.building')),
            ],
        ),
    ]
