# Generated by Django 3.2.7 on 2022-05-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AMS_app.apartmenttype'),
        ),
    ]
